### ISSUE TITLE
fails on every syntax

### ISSUE THREAD

**Issue by thrynae** [lukaspirpamer/simple_JsonDecode#1]
Since `varargin` is always a cell, any call with an input argument will go to the empty `else` branch, leading to an error for `fileread` (because the variable is not yet defined).

Even when calling this without an input argument I could not get it to work. Can you provide an example of how to run this? When trying the example in the help text it tried to include the double quotes in the field name.

**Comment by lukaspirpamer** [comment]
Thank you very much for the bug report!
The varargin mistake is now corrected.
